# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: E:/Computer_System_learning/Vivado/Lab10/Lab10-code/constrs/nexys_a7.xdc

# IP: E:/Computer_System_learning/Vivado/Lab10/Lab10-code/ip/Ram/Ram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Ram || ORIG_REF_NAME==Ram} -quiet] -quiet
