# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 4
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/Computer_System_learning/Vivado/Lab10/Lab10.cache/wt [current_project]
set_property parent.project_path E:/Computer_System_learning/Vivado/Lab10/Lab10.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/Computer_System_learning/Vivado/Lab10/Lab10.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files E:/Computer_System_learning/Vivado/Lab10/Lab10-code/coe/kernel.coe
add_files E:/Computer_System_learning/Vivado/Lab10/Lab10-code/coe/kernel_test.coe
add_files E:/Computer_System_learning/Vivado/Lab10/Lab10-code/coe/lab2.coe
read_verilog E:/Computer_System_learning/Vivado/Lab10/Lab10-code/src/AluOp.vh
read_verilog -library xil_defaultlib -sv {
  E:/Computer_System_learning/Vivado/Lab10/Lab10-code/src/IO_Manager.sv
  E:/Computer_System_learning/Vivado/Lab10/Lab10-code/src/Top.sv
}
read_verilog -library xil_defaultlib {
  E:/Computer_System_learning/Vivado/Lab10/Lab10.srcs/sources_1/new/ALU.v
  E:/Computer_System_learning/Vivado/Lab10/Lab10-code/src/Control.v
  E:/Computer_System_learning/Vivado/Lab10/Lab10-code/src/Core.v
  E:/Computer_System_learning/Vivado/Lab10/Lab10.srcs/sources_1/new/D_cache.v
  E:/Computer_System_learning/Vivado/Lab10/Lab10.srcs/sources_1/new/Datapath.v
  E:/Computer_System_learning/Vivado/Lab10/Lab10.srcs/sources_1/new/ForwardingUnit.v
  E:/Computer_System_learning/Vivado/Lab10/Lab10.srcs/sources_1/new/I_cache.v
  E:/Computer_System_learning/Vivado/Lab10/Lab10.srcs/sources_1/new/ImmGen.v
  E:/Computer_System_learning/Vivado/Lab10/Lab10.srcs/sources_1/new/LatencyMemory.v
  E:/Computer_System_learning/Vivado/Lab10/Lab10.srcs/sources_1/new/LatencyMemory2.v
  E:/Computer_System_learning/Vivado/Lab10/Lab10.srcs/sources_1/new/MUX2T1_32.v
  E:/Computer_System_learning/Vivado/Lab10/Lab10.srcs/sources_1/new/MUX3T1_A.v
  E:/Computer_System_learning/Vivado/Lab10/Lab10.srcs/sources_1/new/MUX3T1_B.v
  E:/Computer_System_learning/Vivado/Lab10/Lab10.srcs/sources_1/new/MUX4T1_32.v
  E:/Computer_System_learning/Vivado/Lab10/Lab10.srcs/sources_1/new/Regs.v
  E:/Computer_System_learning/Vivado/Lab10/Lab10-code/src/SCPU.v
  E:/Computer_System_learning/Vivado/Lab10/Lab10.srcs/sources_1/new/mem_valid_counter.v
  E:/Computer_System_learning/Vivado/Lab10/Lab10.srcs/sources_1/new/next_pc.v
}
read_ip -quiet E:/Computer_System_learning/Vivado/Lab10/Lab10-code/ip/Ram/Ram.xci
set_property used_in_implementation false [get_files -all e:/Computer_System_learning/Vivado/Lab10/Lab10-code/ip/Ram/Ram_ooc.xdc]

read_ip -quiet E:/Computer_System_learning/Vivado/Lab10/Lab10.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all e:/Computer_System_learning/Vivado/Lab10/Lab10.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]

read_edif E:/Computer_System_learning/Vivado/Lab10/Lab10-code/src/Control.edf
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/Computer_System_learning/Vivado/Lab10/Lab10-code/constrs/nexys_a7.xdc
set_property used_in_implementation false [get_files E:/Computer_System_learning/Vivado/Lab10/Lab10-code/constrs/nexys_a7.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Top -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Top_utilization_synth.rpt -pb Top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
